# Site settings
title: roland đorđević online
email: mail@rdo.onl
description: "Experimental projects playground. Roland Đorđević."
baseurl: ""
url: "http://rdo.onl"
twitter_username: rdorde
github_username:  rdorde

# Build settings
markdown: kramdown
permalink: /:title

# Sass settings
sass:
  style: :compressed
